[build]
command = "cd Kaiser-FrontEnd && npm install && npm run build"
publish = "Kaiser-FrontEnd/out"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "cd Kaiser-FrontEnd && npm run dev"
port = 3000
